twig:
    file_name_pattern: '*.twig'
    paths:
        # directories are relative to the project root dir (but you
        # can also use absolute directories)
        '%kernel.project_dir%/public/dist/': dist

when@test:
    twig:
        strict_variables: true
